version: '3'
services:

  visualizer:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 8888:8080

  frontend:
    image: ripa1/list-app
    depends_on:
      - backend
    ports:
      - 80:80

  backend:
    image: ripa1/rust-list-be
    depends_on:
      - mydb
    ports:
      - 8080:8080
    environment:
      - SERVER_ADDR=0.0.0.0:8080
      - PG.USER=test
      - PG.PASSWORD=test
      - PG.HOST=mydb
      - PG.PORT=5432
      - PG.DBNAME=test
      - PG.POOL.MAX_SIZE=16

  mydb:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test

volumes:
  db-data:
    driver: local
